"""Recalculate human-review tables and exploratory statistics from the preserved export."""
import argparse
from collections import Counter, defaultdict
import hashlib
import json
from pathlib import Path
from analysis_metrics import mcnemar_exact, wilson95
from review_history import summarize_history
from experiment_figures import adequacy_figure
from review_reason_labels import REASON_LABELS

ROOT = Path(__file__).resolve().parents[1]
DEFAULT = ROOT/'output/revisao/avaliacao-humana-simplificada-2026-09-27.json'
CLARIFICATION = ROOT/'output/revisao/esclarecimento-avaliacao-humana-2026-09-28.json'
METHODS = [('heuristic','1: heurístico'),('fts','2: FTS + LLM'),
           ('neuro_symbolic','3: vetor + LLM + revisão'),('vector','4: vetor + LLM')]
REASONS = REASON_LABELS


def table(caption, label, columns, header, rows, note):
    body='\n'.join(' & '.join(map(str,row))+r' \\' for row in rows)
    return ('% Generated by generate_human_review_tables.py; do not edit numbers manually.\n'
            r'\begin{table}[htbp]'+'\n'+r'\centering\small'+'\n'
            +r'\caption{'+caption+'}\n'+r'\label{'+label+'}\n'
            +r'\begin{tabular}{'+columns+'}\n'+r'\hline'+'\n'
            +' & '.join(header)+r' \\'+'\n'+r'\hline'+'\n'+body+'\n'
            +r'\hline'+'\n'+r'\end{tabular}'+'\n'
            +r'\fonte{Julgamentos globais de respostas e bloqueios realizados pelo autor. '+note+'}\n'
            +r'\end{table}'+'\n')


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--reviews',type=Path,default=DEFAULT)
    parser.add_argument('--clarification',type=Path,default=CLARIFICATION)
    args=parser.parse_args();raw=args.reviews.read_bytes();data=json.loads(raw)
    clarification_raw=args.clarification.read_bytes();clarification=json.loads(clarification_raw)
    assert clarification['schema_version']==1
    assert clarification['review_export_sha256']==hashlib.sha256(raw).hexdigest()
    interpretation=clarification['interpretation']
    assert interpretation['block_incorrect_means_response_adequate_for_delivery'] is True
    assert interpretation['block_correct_implies_response_inadequate'] is False
    assert clarification['original_judgments_changed'] is False
    assert data['schema_version']==2 and data['protocol']['name']=='simplified_global_judgment'
    assert data['progress']=={'pending':0,'draft':0,'completed':400} and not data['excluded']
    records=data['records'];assert len(records)==400
    by_key={(r['case_id'],r['method']):r for r in records};assert len(by_key)==400
    cases={r['case_id'] for r in records};assert len(cases)==100
    assert set(by_key)=={(cid,m) for cid in cases for m,_ in METHODS}
    history=summarize_history(records,data['history'])
    counts=defaultdict(Counter);causes=defaultdict(Counter)
    for r in records:
        review=r['review'];assert review['status']=='completed'
        v=review['judgment']['verdict'];assert v in {'correct','incorrect'}
        target=r['target'];assert target in {'block','response'}
        assert (r['execution_status']=='blocked')==(target=='block')
        assert r['response_kind']==('blocked_final_draft' if target=='block' else 'delivered')
        counts[r['method']][target+'_'+v]+=1
        if target=='block':
            assert r['method']=='neuro_symbolic'
            reasons=r['blocking']['reasons'];assert len(reasons)==1
            assert reasons[0]['code'] in REASONS
            causes[reasons[0]['code']][v]+=1
    rows=[];intervals={}
    for method,label in METHODS:
        c=counts[method];correct=c['response_correct'];wrong=c['response_incorrect'];total=correct+wrong
        intervals[method]={
            'adequacy_among_delivered':dict(successes=correct, denominator=total, proportion=correct/total, wilson95=wilson95(correct,total)),
            'adequate_delivery':dict(successes=correct, denominator=len(cases), proportion=correct/len(cases), wilson95=wilson95(correct,len(cases))),
        }
        def percentage_ci(metric):
            lo,hi=metric['wilson95']
            return f"{100*metric['proportion']:.1f} [{100*lo:.1f}; {100*hi:.1f}]".replace('.',',')
        rows.append([label.split(':')[0],f'{correct}/{total}',percentage_ci(intervals[method]['adequacy_among_delivered']),
                     f'{correct}/{len(cases)}',percentage_ci(intervals[method]['adequate_delivery'])])
    response_rows=rows
    out=ROOT/'latex/generated';out.mkdir(exist_ok=True)
    (out/'fig_adequacao.tex').write_text(adequacy_figure(intervals))
    rows=[]
    for target,label in [('response','Resposta'),('block','Bloqueio')]:
        v=history['groups'][target]
        rows.append([label,v['items'],v['saves'],v['resaved_items'],v['verdict_changes'],
                     v['first_verdicts'].get('incorrect',0),v['final_verdicts'].get('incorrect',0)])
    (out/'humana_historico.tex').write_text(table(
        'Gravações e alterações dos julgamentos humanos','tab:humana_historico','lrrrrrr',
        ['Objeto','Itens',r'\shortstack{Gravações}',r'\shortstack{Itens\\regravados}',r'\shortstack{Trocas de\\rótulo}',
         r'\shortstack{Incorretos na\\primeira gravação}',r'\shortstack{Incorretos na\\consolidação}'],rows,
        'Regravar um item não implica trocar seu rótulo. Incorreto refere-se à resposta ou ao bloqueio, conforme a linha; os dois objetos não formam uma medida única de qualidade do texto.'))
    rows=[]
    for target,label in [('response','Resposta'),('block','Bloqueio')]:
        v=history['groups'][target]['gaps_ending_at_target']
        rows.append([label,v['n'],*[f'{v[k]:.2f}'.replace('.',',') for k in ['median','p95','maximum']]])
    v=history['consecutive_gaps']
    rows.append(['Todos',v['n'],*[f'{v[k]:.2f}'.replace('.',',') for k in ['median','p95','maximum']]])
    (out/'humana_intervalos_gravacoes.tex').write_text(table(
        'Intervalos entre gravações consecutivas, em segundos','tab:humana_intervalos_gravacoes','lrrrr',
        ['Objeto da gravação posterior','Intervalos','Mediana','P95','Máximo'],rows,
        'Ordem cronológica das 407 gravações. O primeiro registro não possui intervalo anterior. Os intervalos podem incluir navegação e interrupções e não medem tempo de leitura ou esforço de avaliação.'))
    (out/'humana_respostas.tex').write_text(table('Adequação e disponibilidade de respostas com intervalos de Wilson','tab:humana_respostas','lp{2.1cm}p{3.5cm}p{2.1cm}p{3.5cm}',
        ['Método',r'\shortstack[l]{Adequadas/\\entregues}',r'\shortstack[l]{\% das entregas\\IC 95\%}',r'\shortstack[l]{Adequadas/\\perguntas}',r'\shortstack[l]{\% das perguntas\\IC 95\%}'],response_rows,
        'Adequação entre entregas e disponibilidade usam o mesmo numerador e denominadores distintos. Os intervalos se referem a cada proporção, não à diferença entre métodos.'))
    rows=[[label,causes[code]['correct'],causes[code]['incorrect'],sum(causes[code].values())] for code,label in REASONS.items()]
    rows.append(['Total',sum(c['correct'] for c in causes.values()),sum(c['incorrect'] for c in causes.values()),sum(sum(c.values()) for c in causes.values())])
    (out/'humana_bloqueios.tex').write_text(table('Adequação dos bloqueios por motivo registrado no Método 3','tab:humana_bloqueios','p{6.7cm}rrr',
        ['Motivo do sistema','Adequados','Inadequados','Total'],rows,
        'Bloqueio inadequado indica resposta julgada globalmente adequada e passível de entrega. Bloqueio adequado não atribui rótulo de qualidade ao texto.'))
    pairs={}
    for a,b in [('fts','vector'),('neuro_symbolic','vector')]:
        common=[cid for cid in cases if by_key[cid,a]['target']==by_key[cid,b]['target']=='response']
        count=Counter((by_key[cid,a]['review']['judgment']['verdict'],by_key[cid,b]['review']['judgment']['verdict']) for cid in common)
        pairs[a+'__'+b]={'n':len(common),'both_correct':count['correct','correct'],'only_first_correct':count['correct','incorrect'],
                         'only_second_correct':count['incorrect','correct'],'both_incorrect':count['incorrect','incorrect']}
        p=pairs[a+'__'+b]
        p['mcnemar_exact_two_sided_p']=mcnemar_exact(p['only_first_correct'],p['only_second_correct'])
        p['difference_percentage_points']=100*(p['only_first_correct']-p['only_second_correct'])/p['n']
    rows=[]
    for key,label in [('fts__vector','Métodos 2 e 4'),('neuro_symbolic__vector','Métodos 3 e 4')]:
        p=pairs[key];rows.append([label,p['n'],p['both_correct'],p['only_first_correct'],p['only_second_correct'],p['both_incorrect']])
    (out/'humana_pareada.tex').write_text(table('Julgamentos das respostas em casos com entrega comum','tab:humana_pareada','p{2.7cm}rp{2cm}p{2cm}p{2cm}p{2cm}',
        ['Comparação','Casos','Ambos corretos','Só o primeiro correto','Só o segundo correto','Ambos incorretos'],rows,
        'A ordem dos métodos identifica o primeiro e o segundo em cada linha.'))
    rows=[]
    for key,label in [('fts__vector','Métodos 2 e 4'),('neuro_symbolic__vector','Métodos 3 e 4')]:
        p=pairs[key]
        rows.append([label,p['n'],f"{p['difference_percentage_points']:+.1f}".replace('.',','),
                     f"{p['mcnemar_exact_two_sided_p']:.3f}".replace('.',',')])
    (out/'humana_mcnemar.tex').write_text(table('Comparação exploratória da adequação nas entregas comuns','tab:humana_mcnemar','lrp{3.8cm}r',
        ['Comparação','Casos',r'\shortstack[l]{Diferença em pontos\\percentuais}',r'$p$ exato bilateral'],rows,
        'Diferença do primeiro método em relação ao segundo. Teste de McNemar condicionado aos quatro pares discordantes em cada comparação. Valores de $p$ sem ajuste por multiplicidade; interpretação exploratória.'))
    availability={}
    for method,_ in METHODS:
        c=counts[method]
        availability[method]={
            'total_questions':len(cases),
            'delivered_adequate':c['response_correct'],
            'delivered_inadequate':c['response_incorrect'],
            'blocked_adequate_for_delivery':c['block_incorrect'],
            'blocked_text_adequacy_unclassified':c['block_correct'],
            'adequate_text_lower_bound':c['response_correct']+c['block_incorrect'],
        }
        assert sum(availability[method][k] for k in (
            'delivered_adequate','delivered_inadequate','blocked_adequate_for_delivery',
            'blocked_text_adequacy_unclassified'))==len(cases)
    m3=availability['neuro_symbolic']
    rows=[['Adequadas e entregues',m3['delivered_adequate']],
          ['Inadequadas e entregues',m3['delivered_inadequate']],
          ['Adequadas e bloqueadas',m3['blocked_adequate_for_delivery']],
          ['Bloqueios adequados; conteúdo sem classificação independente',m3['blocked_text_adequacy_unclassified']]]
    (out/'humana_disponibilidade.tex').write_text(table(
        'Adequação global e decisão de entrega no Método 3','tab:humana_disponibilidade','p{11cm}r',
        ['Resultado','Casos'],rows,
        'As linhas são mutuamente exclusivas e somam 100 casos. O significado de bloqueio inadequado foi explicitado após a consolidação.'))
    metrics={'export_sha256':hashlib.sha256(raw).hexdigest(),'inputs':data['inputs'],'counts':dict(counts),'blocking_reasons':dict(causes),'pairs':pairs,'clarification_sha256':hashlib.sha256(clarification_raw).hexdigest(),
             'clarified_on':clarification['clarified_on'],'adequacy_and_delivery':availability,'proportion_intervals':intervals,'review_history':history}
    (ROOT/'output/revisao/metricas-avaliacao-humana-2026-09-27.json').write_text(json.dumps(metrics,ensure_ascii=False,indent=2)+'\n')
    print(json.dumps(metrics['counts'],ensure_ascii=False))

if __name__=='__main__':main()
